HomeWork1 work1 = new HomeWork1();
HomeWork2 work2 = new HomeWork2();
HomeWork3 work3 = new HomeWork3();
HomeWork4 work4 = new HomeWork4();
HomeWork5 work5 = new HomeWork5();

Console.WriteLine("Задача 1:");
work1.sort(work1.doubleMass());
Console.WriteLine();
Console.WriteLine("Задача 2:");
work2.doubleMass();
Console.WriteLine();
Console.WriteLine("Задача 3:");
work3.matrixMult();
Console.WriteLine();
Console.WriteLine("Задача 4:");
work4.triplMass();
Console.WriteLine();
Console.WriteLine("Задача 5:");
work5.doubleMass();